{
    size:[42,66],
    offset:[0,0],
    tag:'div',            
    attr:{
        'class':'noselect',
        //src:'/img/units/human/peasant/1b.png'
    },            
    css:{            
        zIndex:99999,
        position:'absolute',
        backgroundImage:'url(/img/units/human/peasant/1b.png)',
        backgroundSize:'cover',
        '-webkit-background-size':'cover',
        backgroundPosition:'center'
    }
}